### ISSUE TITLE
Doesn't work with python 3.9

### ISSUE THREAD

**Issue by monga** [cemc/python3jail#2]
When used with python 3.9 it fails with this error:
```
ImportError: cannot import name 'escape' from 'cgi' (/lib/python3.9/cgi.py)
```
In fact, this is deprecated since python 3.2 (and removed since python 3.8)

It can be easily fixed by importing the symbol from `html` instead (in `_UTILITIES.py`)

**Comment by daveagp** [comment]
Fixed with your patch, ty
